services:
  mq1:
    image: "ibm-mq-server"
    stdin_open: true
    ports:
      - 11443:9443
      - 11414:1414
    networks:
      - qm1network
  mq2:
    image: "ibm-mq-server"
    stdin_open: true
    ports:
      - 10443:9443
      - 10414:1414
    networks:
      - qm1network
networks:
  qm1network:
    labels:
      - com.ibm.mq=qm1